apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sp-kodeverk
  namespace: speilvendt
  annotations:
    snorlax.nais.io/enabled: 'false'
  labels:
    team: speilvendt
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://sp-kodeverk.ekstern.dev.nav.no
  replicas:
    min: 1
    max: 1
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  preStopHook:
    http:
      path: /api/internal/preStop
      port: 3000
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: false
      claims:
        extra:
          - 'NAVident'
        groups:
          - id: 'd606f784-0335-4fbd-9879-e617b48526e0' # helseytelser-spillerom-kodeverk-admin
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /_next/*
        - /public/*
        - /api/v1/open/*
  gcp:
    buckets:
      - name: helse-sp-kodeverk
  resources:
    limits:
      memory: 350Mi
    requests:
      cpu: 50m
      memory: 256Mi
  liveness:
    path: /api/internal/isAlive
  readiness:
    path: /api/internal/isAlive
  startup:
    path: /api/internal/isAlive
    initialDelay: 10
